### ISSUE TITLE
Not working after downloaded as a zip file

### ISSUE THREAD

**Issue by amitchoubey** [jperl/paper#1]
After downloading I run the paper.html file but its not showing anything, that's bcoz nothing define in this html file so how can I run locally after download, If it's not updated then please update it.

**Comment by jperl** [comment]
It is a meteor app. You will need to run [meteor](http://docs.meteor.com/#quickstart).

**Comment by amitchoubey** [comment]
And If I wanted to run this code without meteor then how can I do?

**Comment by jperl** [comment]
It's not possible w/ this example but I am working on publishing a paper component that will be useable outside of meteor. Stay tuned.
